version: "2"
plugins:
  eslint:
    enabled: true
  pep8:
    enabled: true
  rubocop:
    enabled: true
  editorconfig:
    enabled: true
exclude_patterns:
- "services/web/db/schema.rb"
- "services/web/bin/"
- "services/web/babel.config.js"
