#os: linux
#arch:
#  - amd64
#  - arm64
#
#services:
#  - docker

jobs:
  include:
    - language: ruby
      cache:
        yarn: true
        bundler: true
      before_install:
        - cd services/web
        - gem install bundler
        - nvm install node
        - nvm use node
        - curl -o- -L https://yarnpkg.com/install.sh | bash
      install:
        - bundle install --jobs 4 --without development --deployment
        - yarn install --production --frozen-lockfile
    rvm: 2.5.7
      env:
        - RAILS_ENV=test
      script:
        - bundle exec rails db:migrate
        - bundle exec rails test
#        - docker build -t ftes/clickr-rails-web .
#    - language: python
#      cache: pip
#      before_install:
#        - cd services/rfid-keyboard-reader
#      install:
#        - pip install -r requirements.txt
#      script:
#        - docker build -t ftes/clickr-rails-rfid-keyboard-reader .
# TODO balena push
