language: ruby
cache:
  yarn: true
  bundler: true
before_install:
  - cd services/web
  - gem install bundler
  - nvm install node
  - nvm use node
  - curl -o- -L https://yarnpkg.com/install.sh | bash
install:
  - bundle install --jobs 4 --without development --deployment
  - yarn install --production --frozen-lockfile
rvm:
  - 2.5.7
env:
  - RAILS_ENV: test
script:
  - bundle exec rails db:migrate
  - bundle exec rails test
