language: ruby
cache:
  yarn: true
  bundler: true
before_install:
  - cd services/web
  - gem install bundler
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
install:
  - bundle install --jobs 4 --without development test --deployment
  - yarn install --production --frozen-lockfile
rvm:
  - 2.5.7
env:
  - RAILS_ENV: test
script:
  - bundle exec rails db:migrate
  - bundle exec rails test
