version: '3.5'
services:
  db:
    image: postgres:alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    expose:
      - 5432

  web:
    build: .
    environment:
      - DATABASE_HOST=db
    expose:
      - 3000
    depends_on:
      - db

volumes:
  postgres:
