version: '2'
services:
  web:
    build: .
    environment:
      - DATABASE_HOST=db
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    expose:
      - 3000
    volumes:
      - db:/usr/src/app/db
    ports:
      - 80:3000

volumes:
  db:
