version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/build/balena-cli"
    update_schedule: "live"

  - package_manager: "ruby:bundler"
    directory: "/services/web"
    update_schedule: "live"

  - package_manager: "javascript"
    directory: "/services/web"
    update_schedule: "live"

  - package_manager: "python"
    directory: "/services/rfid-keyboard-reader"
    update_schedule: "live"
